medconnect/urls.py
from medconnect.views import *
from django.urls import path

urlpatterns = [
    path('', index, name='index'),
    path("atendimento", locais_de_atendimento, name='locais_de_atendimento'),
    path("atendimento/", buscar, name='buscar'),
    path("informacoes/<int:hospital_cnes>", mais_informacoes, name='mais_informacoes'),
    path("avaliar/<int:hospital_cnes>", avaliar_hospital, name='avaliar_hospital'),
    path("duvidas_frequentes", duvidas_frequentes, name='duvidas_frequentes'),
    path("sobrenos", sobre_nos, name="sobre_nos"),
    path("cadastro", cadastro, name='cadastro'),
    path("login", login_site, name='login'),
    path("login/confirmacao", confirma_email, name="confirma_email"),
    path("logout", logout_site, name="logout"),
    path("redefinir_senha/<str:username>/<str:token>", redefinir_senha, name="redefinir_senha"),
    path("perfil/avaliacoes", minhas_avaliacoes, name="minhas_avaliacoes"),
    path("perfil/avaliacoes/", pesquisar_avaliacoes, name="pesquisar_avaliacoes"),
    path("perfil/avaliacoes/<int:avaliacao_id>", avaliacao_completa, name="avaliacao_completa"),
    path("perfil/meus_dados", meus_dados, name="meus_dados"),
    path("perfil/editar_dados", editar_dados, name="editar_dados"),
    path("triagem", triagem, name="triagem"),
    path("triagem/a1",adulto1, name="adulto1"),
    path("triagem/a2",adulto2, name="adulto2"),
    path("triagem/a3",adulto3, name="adulto3"),
    path("triagem/a4",adulto4, name="adulto4"),
    path("triagem/b1",crianca1, name="crianca1"),
    path("triagem/b2",crianca2, name="crianca2"),
    path("triagem/b3",crianca3, name="crianca3"),
    path("triagem/b4",crianca4, name="crianca4"),
    path("resultado_vermelho",resultado_vermelho, name="resultado_vermelho"),
    path("resultado_laranja",resultado_laranja, name="resultado_laranja"),
    path("resultado_amarelo",resultado_amarelo, name="resultado_amarelo"),
    path("resultado_verde",resultado_verde, name="resultado_verde"),
    path("resultado_azul",resultado_azul, name="resultado_azul"),
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = 'MedConnect'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('medconnect.urls'))
]

medconnect/models.py
from django.db import models

from django.db import models
from django.utils import timezone
from datetime import date, timedelta
from django.contrib.auth.models import User

class Hospital(models.Model):

    class Meta:
        verbose_name_plural = "Hospitais"

    CATEGORIAS = [
        ("HOSPITAL_PUBLICO", "Público"),
        ("HOSPITAL_PRIVADO", "Privado"),
        ("HOSPITAL_FILANTROPICO", "Filantrópico")
    ]

    UFS = [
        ("AC","Acre"),
        ("AL","Alagoas"),
        ("AP","Amapá"),
        ("AM","Amazonas"),
        ("BA","Bahia"),
        ("CE","Ceará"),
        ("DF","Distrito Federal"),
        ("ES","Espirito Santo"),
        ("GO","Goiás"),
        ("MA","Maranhão"),
        ("MT","Mato Grosso"),
        ("MS","Mato Grosso do Sul"),
        ("MG","Minas Gerais"),
        ("PA","Pará"),
        ("PB","Paraíba"),
        ("PR","Paraná"),
        ("PE","Pernambuco"),
        ("PI","Piauí"),
        ("RJ","Rio de Janeiro"),
        ("RN","Rio Grande do Norte"),
        ("RS","Rio Grande do Sul"),
        ("RO","Rondônia"),
        ("RR","Roraima"),
        ("SC","Santa Catarina"),
        ("SP","Sâo Paulo"),
        ("SE","Sergipe"),
        ("TO","Tocantins")
    ]

    cnes = models.CharField(max_length=7, null=False, blank=False, primary_key=True, default="0000000", editable=False)
    nome = models.CharField(max_length=100, null=False, blank=False)
    endereco = models.CharField(max_length=150, null=False, blank=False)
    cep = models.CharField(max_length=20, null=False, blank=False)
    categoria = models.CharField(max_length=100, choices=CATEGORIAS, default='')
    uf = models.CharField(max_length=100, choices=UFS, default='')
    municipio = models.CharField(max_length=150,  default='')
    telefone = models.CharField(max_length=100, null=False, blank=False, default="Não informado")
    email = models.CharField(max_length=100, null=False, blank=False, default="Não informado")
    tempo_emergente = models.IntegerField(null=False, blank=False, default=0)
    tempo_muito_urgente = models.IntegerField(null=False, blank=False, default=0)
    tempo_urgente = models.IntegerField(null=False, blank=False, default=0)
    tempo_pouco_urgente = models.IntegerField(null=False, blank=False, default=0)
    tempo_nao_urgente = models.IntegerField(null=False, blank=False, default=0)
    nota = models.DecimalField(max_digits=4, decimal_places=3, null=False, blank=False, default=0)
    leitos = models.IntegerField(null=False, blank=False, default=0)
    uti_adulto = models.IntegerField(null=False, blank=False, default=0)
    uti_pediatrico = models.IntegerField(null=False, blank=False, default=0)
    uti_neonatal = models.IntegerField(null=False, blank=False, default=0)
    uti_queimado = models.IntegerField(null=False, blank=False, default=0)
    atualizacao = models.DateTimeField(null=False, blank=False, default=timezone.now)

    def __str__(self):
        return self.nome

class Avaliacao(models.Model):

    class Meta:
        verbose_name = "avaliação"
        verbose_name_plural = "Avaliações"

    RISCO = [
        ("EMERGENTE", "Emergente"),
        ("MUITO_URGENTE", "Muito Urgente"),
        ("URGENTE", "Urgente"),
        ("POUCO_URGENTE", "Pouco Urgente"),
        ("NAO_URGENTE", "Não Urgente")
    ]

    usuario = models.CharField(max_length=100, null=False, blank=False, default="")
    numero = models.IntegerField(null=False, blank=False, default=1)
    data = models.DateTimeField(null=False, blank=False, default=timezone.now)
    hospital = models.ForeignKey(Hospital, on_delete=models.CASCADE)
    risco = models.CharField(max_length=100, null=False, blank=False, default="NAO_URGENTE", choices=RISCO)
    horario_entrada = models.DateTimeField(null=False, blank=False, default=timezone.now)
    horario_atendimento = models.DateTimeField(null=False, blank=False, default=timezone.now)
    horario_saida = models.DateTimeField(null=False, blank=False, default=timezone.now)
    duracao = models.DurationField(null=False, blank=False, default=timedelta(minutes=30))
    avaliacao = models.IntegerField(null=False, blank=False, default=3)
    observacao = models.TextField(null=False, blank=False, default="")

    def __str__(self):
        return self.risco

class Dados(models.Model):

    class Meta:
        verbose_name = "dados"
        verbose_name_plural = "Dados"

    GENERO = [
        ("na","Não informado"),
        ("homem-cis", "Homem cis"),
        ("homem-trans", "Homem trans"),
        ("mulher-cis", "Mulher cis"),
        ("mulher-trans", "Mulher trans"),
        ("nao-binario", "Não-binário"),
        ("outro", "Outro")
    ]

    TIPO_SANGUINIO = [
        ("A+","A+"),
        ("A-","A-"),
        ("B+","B+"),
        ("B-","B-"),
        ("AB+","AB+"),
        ("AB-","AB-"),
        ("O+","O+"),
        ("O-","O-"),
        ("na","Não informado/Não sabe")
    ]

    FREQUENCIA = [
        ("n","Não"),
        ("d","Diariamente"),
        ("s","Semanalmente"),
        ("m","Mensalmente"),
        ("a","Anualmente")
    ]

    usuario = models.OneToOneField(User,on_delete=models.CASCADE, primary_key=True)
    data_nascimento = models.DateField(null=False, blank=False, default=timezone.now)
    genero = models.CharField(max_length=20, null=False, blank=False, default="na", choices=GENERO)
    profissao = models.CharField(max_length=200, null=False, blank=False, default="Não informada")
    endereco = models.CharField(max_length=200, null=False, blank=False, default="Não informado")
    telefone = models.CharField(max_length=20, null=False, blank=False, default="Não informado")
    peso = models.DecimalField(max_digits=5, decimal_places=2, null=False, blank=False, default=0)
    altura = models.DecimalField(max_digits=3, decimal_places=2, null=False, blank=False, default=0)
    tipo_sanguineo = models.CharField(max_length=4, null=False, blank=False, default="na", choices=TIPO_SANGUINIO)
    fumo_alcool = models.CharField(max_length=200, null=False, blank=False, default="n", choices=FREQUENCIA)
    exercicio = models.CharField(max_length=200, null=False, blank=False, default="Nâo informado")
    exercicio_frequencia = models.CharField(max_length=200, null=False, blank=False, default="n", choices=FREQUENCIA)

    def __str__(self):
        return self.usuario.username

class Doencas(models.Model):

    class Meta:
        verbose_name = "doença"
        verbose_name_plural = "Doenças"

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="doencas")
    doenca = models.CharField(max_length=200, null=False, blank=False, default="N/A")

    def __str__(self):
        return self.doenca

class Sintomas(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="sintomas")
    sintoma = models.CharField(max_length=200, null=False, blank=False, default="N/A")

    def __str__(self):
        return self.sintoma

class Diagnostico(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="diagnosticos")
    diagnostico = models.CharField(max_length=200, null=False, blank=False, default="N/A")

    def __str__(self):
        return self.diagnostico

class Cirurgia(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="cirurgias")
    cirurgia = models.CharField(max_length=200, null=False, blank=False, default="N/A")
    data = models.DateField(null=False, blank=False, default=timezone.now)

    def __str__(self):
        return self.cirurgia

class Internacao(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="internacoes")
    internacao = models.CharField(max_length=200, null=False, blank=False, default="N/A")
    tempo = models.IntegerField(null=False, blank=False, default=0)
    data = models.DateField(null=False, blank=False, default=timezone.now)

    def __str__(self):
        return self.internacao

class Condicao_familiar(models.Model):

    GRAU_PARENTESCO = [
        ("1", "1° Grau"),
        ("2", "2° Grau"),
        ("3", "3° Grau")
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="condicao_familiar")
    condicao = models.CharField(max_length=200, null=False, blank=False, default="N/A")
    grau_parentesco = models.CharField(max_length=10, null=False, blank=False, default="1", choices=GRAU_PARENTESCO)

    def __str__(self):
        return self.condicao

class Medicamento(models.Model):

    TIPO_MEDICAMENTO = [
        ("1", "Medicamento com prescrição"),
        ("2", "Medicamento sem prescrição")
    ]

    FREQUENCIA = [
        ("n","Não"),
        ("d","Diariamente"),
        ("s","Semanalmente"),
        ("m","Mensalmente"),
        ("a","Anualmente")
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="medicamentos")
    tipo = models.CharField(max_length=200, null=False, blank=False, default="1", choices=TIPO_MEDICAMENTO)
    medicamento = models.CharField(max_length=200, null=False, blank=False, default="N/A")
    frequencia = models.CharField(max_length=200, null=False, blank=False, default="n", choices=FREQUENCIA)
    numero_frequencia = models.IntegerField(null=False, blank=False, default=0)

    def __str__(self):
        return self.medicamento

medconnect/forms.py
from django import forms
from .models import *

class BuscarForms(forms.Form):
    buscar = forms.CharField(
        max_length=100,
        label='',
        required=False,
        widget=forms.TextInput(
            attrs={
                "id":"txtPesquisar",
                "placeholder":"Pesquisar..."
            }
        )
    )

class FilterForms(forms.Form):

    CHOICES = []
    sub_choices = ["",""]
    CHOICES.append(sub_choices)

    for i, j in Hospital.UFS:
        sub_choices = [i,j]
        CHOICES.append(sub_choices)

    uf = forms.ChoiceField(
        required=False,
        choices=CHOICES,
        widget=forms.Select(
            attrs={
                "class":"select-uf",
                "style":"width: 100%"
            }
        )
    )

    CHOICES = []
    sub_choices = ["",""]
    CHOICES.append(sub_choices)

    for i, j in Hospital.objects.values_list("municipio", "uf").distinct():
        sub_choices = [i,f"{i} - {j}"]
        CHOICES.append(sub_choices)

    municipio = forms.ChoiceField(
        required=False,
        choices=CHOICES,
        widget=forms.Select(
            attrs={
                "class":"select-municipio",
                "style":"width: 100%"
            }
        )
    )
    
    CHOICES = []
    sub_choices = ["",""]
    CHOICES.append(sub_choices)

    for i, j in Hospital.CATEGORIAS:
        sub_choices = [i,j]
        CHOICES.append(sub_choices)

    categoria = forms.ChoiceField(
        required=False,
        choices=CHOICES,
        widget=forms.Select(
            attrs={
                "class":"select-categoria",
                "style":"width: 100%"
            }
        )
    )

    especialidade = forms.ChoiceField(
        required=False,
        widget=forms.Select(
            attrs={
                "class":"select-especialidade",
                "style":"width: 100%"
            }
        )
    )

class CadastroForms(forms.Form):
    email = forms.EmailField(
        label="E-mail",
        required=True,
        max_length=100,
        widget=forms.TextInput(
            attrs={
                "placeholder":"Digite seu e-mail"
            }
        )
    )

    nome_cadastro = forms.CharField(
        label="Usuário",
        required=True,
        max_length=100,
        widget=forms.TextInput(
            attrs={
                "placeholder": "Digite seu nome de usuário"
            }
        )
    )

    senha_1 = forms.CharField(
        label="Senha",
        required=True,
        max_length=70,
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Digite sua senha"
            }
        )
    )

    senha_2 = forms.CharField(
        label="Confirme sua senha",
        required=True,
        max_length=70,
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Confirme sua senha"
            }
        )
    )

templates/medconnect/SobreNos.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Página - Sobre nós</title>
    <link rel="shortcut icon" href="../img/favicon_io/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="{% static "styles/header_e_footer.css"%}">
    <link rel="stylesheet" href="{% static "styles/sobre_nos.css"%}">
    <link rel="stylesheet" href="{% static "styles/FazerLogin.css"%}">
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <style>
        .material-symbols-outlined {
            font-variation-settings:
            'FILL' 10,
            'wght' 200,
            'GRAD' 0,
            'opsz' 36;
            z-index: 1;
            font-size: 36px;
            color: gray;
            font-family: 'Material Symbols Outlined';
        }
    </style>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="{% static "js/select.js" %}"></script>
    <script src="{% static "js/login.js" %}"></script>
    <script src="{% static "js/barra_pesquisa.js"%}"></script>
    <script src="{% static "js/login_popup.js"%}"></script>
</head>
<body>
    <!-- MENU SUPERIOR -->
    {% include "medconnect/partials/_login.html" %}
    {% include "medconnect/partials/_header.html" %} 
    <main>
        <span>
            <article>
                <h1>QUEM SOMOS</h1>
                    <p>
                        Somos um grupo de estudantes da faculdade do Gama da Universidade de Brasília. O site desenvolvido se trata de um projeto da disciplina "Desenvolvimento de Software", componente curricular do programa de graduação em Engenharia de Software. 
                    </p>
                    <p>
                        Através do desenvolvimento deste site, almejamos apresentar um projeto produtivo e que oferte à sociedade um serviço que agregue na vida cotidiana das pessoas, em relação ao atendimento à saúde.
                    </p>
            </article>
            <article>
                <h1>OBJETIVO DO SITE</h1>
                    <p>
                        O site MedConnect tem como objetivo principal fornecer informações seguras ao usuário sobre os pontos de atendimento à saúde mais próximos à sua localização, permitindo uma prévia noção das possibilidades de atendimento ao seu caso, de modo a otimizar o planejamento do usuário, no intuito de ajudar a reduzir as chances de agravamento de sua situação de saúde.
                    </p>
                    <p>
                        Nesse sentido, o enfoque é apresentar estimativas do tempo médio de espera para o atendimento em cada unidade de saúde próxima ao usuário, com base em informações cedidas pelos próprios usuários do site acerca do atendimento recebido em determinada unidade.
                    </p>
                    <p>
                        Na mesma linha, facilita-se o acesso a informações gerais a respeito de cada unidade de saúde, como logradouro, contato, infraestrutura de atendimento e especialidades atendidas. Além dise, apresentam-se informações mais específicas, medicamentos disponíveis e escala de serviço, que são disponibilizadas por órgâos gestores da rede pública de saúde. 
                    </p>
            </article>
        </span>
    </main>
    {% include "medconnect/partials/_footer.html"%}
    <script src="../static/js/togglemenu.js"></script>
</body>
</html>

templates/medconnect/adulto2.html
<!DOCTYPE html>
{% load static %}
<html lang="PT-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pré-triagem | Medconnect</title>
    <link rel="stylesheet" href="{% static "styles/adulto1.css" %}">
    <link rel="stylesheet" href="{% static "styles/header_e_footer.css" %}">
    <link rel="stylesheet" href="{% static "styles/FazerLogin.css"%}">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        body{
            background-color: #ededed;
        }
    </style>
    <style>
        .material-symbols-outlined {
            font-variation-settings:
            'FILL' 10,
            'wght' 200,
            'GRAD' 0,
            'opsz' 36;
            z-index: 1;
            font-size: 36px;
            color: gray;
            font-family: 'Material Symbols Outlined';
        }
    </style>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="{% static "js/select.js" %}"></script>
    <script src="{% static "js/login.js" %}"></script>
    <script src="{% static "js/barra_pesquisa.js"%}"></script>
    <script src="{% static "js/login_popup.js"%}"></script>
</head>
<body>
    {% include "medconnect/partials/_login.html"%}
    {% include "medconnect/partials/_header.html"%}
    <form action="{% url "adulto2" %}" method="POST">
        {% csrf_token %}
        <div class="container_adulto1">
            <h1 class="titule_adulto1">QUESTIONÁRIO DE PRÉ-TRIAGEM</h1>
            <hr/>
            <strong>
            <h2 style="margin-bottom:20px">selecione os seguintes sintomas do paciente</h2>
            </strong>
            <input class="checkbox_adulto1" type="checkbox" name="quest_a2" value="1">
            <label class="subtitule_adulto1" for="quest_a2"> O paciente apresenta dor severa?</label>
            <p class="phrase_adulto1">A dor é descrita como muito forte ou insuportável, pode durar horas ou dias e pode durar horas ou dias. a dor pode piorar outros sintomas, como náusea, vômito ou insônia.</p>
            
            <input class="checkbox_adulto1" type="checkbox" name="quest_a2" value="1">
            <label class="subtitule_adulto1" for="quest_a2"> O paciente está com hemorragia incontrolável?</label>
            <p class="phrase_adulto1">Não é controlada pela aplicação de pressão direta constante e continua a sangrar abundantemente, ensopando rapidamente compressas. Pode ser observada como sangue escorrendo de uma ferida, vômito de sangue, sangue nas fezes ou urina, ou sangue na tosse. Pode apresentar palidez, sudorese, taquicardia, hipotensão e confusão ou perda de consciência</p>
            
            <input class="checkbox_adulto1" type="checkbox" name="quest_a2" value="1">
            <label class="subtitule_adulto1" for="quest_a2">O paciente está com alteração do nível de consciência?</label>            
            <p class="phrase_adulto1">Pode ser causada por lesões cerebrais, infecções, doenças metabólica, medicamentos ou drogas, condições psiquiátricas, dentre outras. Os sintomas leves podem incluir: Sonolência, Dificuldade de concentração, Perda de memória recente. Os sintomas mais graves podem incluir: Letargia, Obnubilação, Torpor e Coma.</p>
            <br>
            <div id="box-button">
                <a href="{%url "adulto1"%}"><input class="btn_adulto1_voltar" type="button" value="voltar"></a>
                <input class="btn_adulto1_continuar" type="submit" value="continuar">
            </div>
        </div>
    </form>
    {% include "medconnect/partials/_footer.html"%}
    <script src="../static/js/togglemenu.js"></script>
</body>
</html>

templates/medconnect/av_completa.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Perfil - Minhas avaliações | MedConnect</title>
    <link rel="stylesheet" href="{% static "styles/header_e_footer.css"%}">
    <link rel="stylesheet" href="{% static "styles/minhasavaliacoes.css"%}">
    <link rel="stylesheet" href="{% static "styles/FazerLogin.css"%}">
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <!--Avaliação em estrelas-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <style>
        .material-symbols-outlined {
            font-variation-settings:
            'FILL' 10,
            'wght' 200,
            'GRAD' 0,
            'opsz' 36;
            z-index: 1;
            font-size: 36px;
            color: gray;
            font-family: 'Material Symbols Outlined';
        }
    </style>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="{% static "js/select.js" %}"></script>
    <script src="{% static "js/login.js" %}"></script>
    <script src="{% static "js/barra_pesquisa.js"%}"></script>
    <script src="{% static "js/login_popup.js"%}"></script>
</head>
<body>
    <!-- MENU SUPERIOR -->
    {% include "medconnect/partials/_login.html" %}
    {% include "medconnect/partials/_header.html" %}
    <main>
        <div id="title">
            <a href="{% url "minhas_avaliacoes" %}"><i class="uil uil-angle-down"></i></a>
            <h1>MINHAS AVALIAÇÕES</h1>
        </div>
        <hr/>

        <h2>AVALIAÇÃO - {{ avaliacao.hospital }}</h2>
    
    <div class="outer_container_av" id="outer1">
        
        <div class="inner_container_av" id="inner0">
            <h3>Av. n° {{ avaliacao.numero }} {{ avaliacao.data|date:"d/m/y"}}</h3>
            <h4>{{ avaliacao.hospital }}</h4>
            <span class="endereco">{{ avaliacao.hospital.endereco }}</span>
            <div class="stars"></div>
            <div class="class_recebida">
                <span>Class. recebida:</span>
                <span class="classificacao">{{ avaliacao.get_risco_display }}<!--<span class="cor">(Laranja)</span>--></span>
            </div>
        </div>
        <hr/>
    <div class="av_box" id="box">
        <!--<div class="group">
            <span class="ask">・ Recebeu atendimento?</span>
            <span class="resp">Sim/Não</span>
        </div>-->
        <div class="group">
            <span class="ask">・ Dia e horário de entrada:</span>
            <span class="dia_hora_entrada">{{ avaliacao.horario_entrada|date:"d/m/y - H:i"}}</span>
        </div>
        <div class="group">
            <span class="ask">・ Dia e horário de saída:</span>
            <span class="dia_hora_saida">{{ avaliacao.horario_saida|date:"d/m/y - H:i"}}</span>
        </div>
        <div class="group" id="avaliacao">
            <span class="ask">・ Avaliação:</span>
            <div class="inner-flex-item" id="estrelas">
                {% for number in counter %}
                    {% if number <= avaliacao.avaliacao %}
                        <span class="fa fa-star checked"></span>
                    {% else %}
                        <span class="fa fa-star"></span>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
        <div class="group">
            <span class="ask">・ Comentários adicionais:</span>
            <span class="comentario">{{ avaliacao.observacao }}</span>
        </div>
    </div>
    </div>
        <!-- <div>
            <a href="../../Página - Avaliar hospital/avaliarhospital.html"><button class="btn_corrigir_av">Corrigir avaliação</button></a>
        </div> -->
    </main>
    {% include "medconnect/partials/_footer.html"%}
    <script src="../static/js/togglemenu.js"></script>
    <!-- Obs.: Avaliação do atendimento recebido abarca se a pessoa recebeu ou não atendimento, o tipo e a forma de atendimento (disponibilidade, empatia, segurança) -->

</body>
</html>